name: proxy

services:
    traefik:
        extends:
            file: ../00_templates/service.yml
            service: public-with-auth
        image: traefik:v3
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - data:/certificates
        command:
            # Enable Traefik management dashboard and healthcheck endpoint
            - --api=true
            - --ping=true
            # Configure log format and verbosity
            - --log.format=json
            - --log.level=INFO
            - --accesslog=true
            - --accesslog.format=json
            # Enable metrics
            - --metrics.prometheus=true
            # Configure docker provider
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --providers.docker.network=public
            # Configure default entrypoints
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
            - --entrypoints.web.http.redirections.entrypoint.scheme=https
            - --entrypoints.web.http.redirections.entrypoint.permanent=true
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http.tls.certresolver=letsencrypt
            # Configure ACME provider and challenge
            - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
            - --certificatesresolvers.letsencrypt.acme.storage=/certificates/acme.json
            - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
        healthcheck:
            test:
                - CMD
                - traefik
                - healthcheck
                - --ping
            interval: 10s
            start_period: 5s
            retries: 3
            timeout: 5s
        labels:
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.service=api@internal

volumes:
    data: {}

include:
    - ../00_templates/networks.yml
