name: auth

services:
    pocketid:
        extends:
            file: ../00_templates/service.yml
            service: public
        image: ghcr.io/pocket-id/pocket-id:v1
        environment:
            APP_URL: https://${COMPOSE_PROJECT_NAME}.${BASE_DOMAIN}
            TRUST_PROXY: true
            PUID: 1000
            PGID: 1000
            ENCRYPTION_KEY: ${ENCRYPTION_KEY}
            ANALYTICS_DISABLED: true
            UI_CONFIG_DISABLED: true
            APP_NAME: GonCas ID
            ALLOW_USER_SIGNUPS: withToken
        expose:
            - 1411
        volumes:
            - data:/app/data
        # Optional healthcheck
        healthcheck:
            test: ["CMD", "/app/pocket-id", "healthcheck"]
            interval: 1m30s
            timeout: 5s
            retries: 2
            start_period: 10s
        labels:
            traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.secret: ${OIDC_SECRET}
            traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.scopes: openid,profile,email
            traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.provider.Url: https://${COMPOSE_PROJECT_NAME}.${BASE_DOMAIN}
            traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.provider.ClientID: ${OIDC_CLIENT_ID}
            traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.provider.ClientSecret: ${OIDC_CLIENT_SECRET}

volumes:
    data: {}

include:
    - ../00_templates/networks.yml
